version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./service-api/public:/var/www/public
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./service-api:/var/www
    environment:
      - APP_ENV=prod
      - DATABASE_URL=postgresql://postgres:password@db:5432/connceservice?serverVersion=16&charset=utf8
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your_jwt_secret
      - JWT_PRIVATE_KEY_PATH=/var/www/config/jwt/private.pem
      - JWT_PASSPHRASE=your_passphrase
      - MERCURE_URL=http://mercure:80/hubs
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: connceservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mercure:
    image: dunglas/mercure:v0.14
    environment:
      - Caddy_CORS_origins=http://localhost:3000,http://localhost:80
      - CADDY_SYSTEMLOG_LEVEL=DEBUG
      - JWT_KEY=<your_jwt_key>
    ports:
      - "8080:80"

volumes:
  postgres_data:
