framework:
    rate_limiter:
        limiters:
            api_anonymous:
                policy: sliding_window
                limit: 60
                interval: '1 minute'
                cache_pool: cache.app
            api_authenticated:
                policy: sliding_window
                limit: 300
                interval: '1 minute'
                cache_pool: cache.app
            login:
                policy: fixed_window
                limit: 10
                interval: '15 minutes'
                cache_pool: cache.app
